#!/usr/bin/perl
use warnings;
use strict;

my ($run_folder,$number_of_lanes) = @ARGV;

unless ($number_of_lanes) {
		die "Usage is make_run_folder_layout [run folder name] [number of lanes]\n";
}

unless ($number_of_lanes =~ /^\d+$/) {
		die "Number of lanes must be an integer\n";
}

unless ($number_of_lanes >0 and $number_of_lanes <9) {
		die "Number of lanes must be between 1 and 8\n";
}

if ($run_folder =~ /\//) {
		die "Run folder must just be the folder name - not a full path\n";
}

if ($run_folder =~ /\s/) {
		die "You can't have spaces in the run folder name\n";
}

if ($run_folder =~ /(\*\?\[\])/) {
		die "You can't have things like '$1' in your run folder name\n";
}

for my $lane (1..$number_of_lanes) {
		system("mkdir -p /primary/${run_folder}/Unaligned/Project_Sanger/Sample_lane${lane}") == 0 or die "Can't make lane $lane for folder $run_folder";
}
